spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      driver-class-name: org.h2.Driver
      username: root
      password: root
  h2:
    console:
      path: /h2
      enabled: true
  sql:
    init:
      schema-locations: classpath:table.sql